title: Aniket Kumar
author: Aniket Kumar
email: anikketkumar786@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  I'm Aniket Kumar a computer Science Undergraduate and software developer 
  contributing to KDE and KDEConnect which is an open source organization. 
  I am a student of Google Summer of code (GSoC 2020).
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /blogpost

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Aniket Kumar
  tagline: Computer Science & Engineering Undergraduate
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    gitlab: https://invent.kde.org/aniketkumar
    github:  https://github.com/anikket786
    linkedIn: https://www.linkedin.com/in/anikketkumar786/
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

gems: 
  - jekyll-sitemap
